# Generated by Django 3.1.4 on 2020-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetabelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
                ('sub5', models.CharField(max_length=100)),
                ('sub6', models.CharField(max_length=100)),
                ('sub7', models.CharField(max_length=100)),
            ],
        ),
    ]
