# Generated by Django 3.1.4 on 2020-12-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_timetabeldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabeldata',
            name='major',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetabeldata',
            name='year',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
