# Generated by Django 3.1.4 on 2020-12-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_auto_20201226_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetabelData',
        ),
    ]
